### ISSUE TITLE
Build + Push task

### ISSUE THREAD

**Issue by hcliu** [sorah/mamiya#25]
It would be nice to be able to build and push with one command, without having to copy and paste the package name.

One solution I came up with is to add a --push option to the `build` task in `cli.rb` - which just calls `push` with the package name after it's built.

Wanted to discuss it before sending a pull request - what do you think?

**Comment by sorah** [comment]
It's acceptable!

FYI, as our use case, we run `mamiya build` and test run simultaneously in CI, then push built package only if test run passed.

**Comment by hcliu** [comment]
requested here: https://github.com/sorah/mamiya/pull/26
